# -*- coding: utf-8 -*-
"""ConvertDICOMtoJPG.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QhzN7afYM8JRkKNB7W8Tt9Xok2rGuhj7
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install -U pynetdicom

import numpy as np
import pydicom as dicom
from PIL import Image

#img_path = '/content/drive/MyDrive/DAEN690/000ae00eb3942d27e0b97903dd563a6e.dicom'
img_path = '/content/drive/MyDrive/DAEN690/000d68e42b71d3eac10ccc077aba07c1.dicom'

im = dicom.dcmread(img_path)
im = im.pixel_array.astype(float)

rescaled_image = (np.maximum(im, 0)/im.max())*255
final_image = np.uint8(rescaled_image)

final_image = Image.fromarray(final_image)
final_image.show()
final_image.save('/content/drive/MyDrive/DAEN690/test.jpg')

import matplotlib.pylab as plt
plt.imshow(final_image)

newsize = (512, 512)
#final_image.resize(newsize)

reload_img = Image.open('/content/drive/MyDrive/DAEN690/test.jpg')
reload_img.show()

reload_img = Image.open('/content/drive/MyDrive/DAEN690/test.jpg')
reload_img.resize(newsize)
#reload_img

folder_dir = '/content/drive/MyDrive/DAEN690/'
output_dir = '/content/drive/MyDrive/DAEN690/jpg_data'

for nextfile in os.listdir(folder_dir):
    base = nextfile.split('.')
    destfile = base[0] + '.jpg'

 
    # check if the image ends with dicom
    if (nextfile.endswith(".dicom")):
        ds = dicom.dcmread(folder_dir+"/"+nextfile)
        #print(nextfile)
        pixarr = ds.pixel_array.astype(float)
# get the path/directory
import os
        rescaled_image = (np.maximum(pixarr, 0)/pixarr.max())*255
        nparr = np.uint8(rescaled_image)

        final_image = Image.fromarray(nparr)
        final_image.save(os.path.join(output_dir, destfile))