# -*- coding: utf-8 -*-
"""LungXRayBarChart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14dyu5P5dSmmCKLj7gGgA1JdhpS_026QP
"""

from google.colab import drive
drive.mount('/content/drive')

pwd()

!ls '/content/drive/MyDrive/DAEN690/'

import pandas as pd
df = pd.read_csv ('/content/drive/MyDrive/DAEN690/train.csv')
print(df)

df.loc[df['image_id'] == '001d127bad87592efe45a5c7678f8b8d']

df

unique_df = df.drop_duplicates()

df.shape

unique_df.shape

df['image_id'].nunique()

df[['image_id', 'class_id']].nunique()

df_plot = df[['image_id', 'class_name']].drop_duplicates()
df_plot.count()

df_plt = df_plot.groupby(['class_name'])['image_id'].count().reset_index()
df_plt.columns = ['Abnormality', 'Count']

#df[['image_id', 'class_id']].drop_duplicates().sort_values('image_id')
df_plt

df.unique()

df.groupby(df.columns.tolist(), as_index=False).size()

import matplotlib.pyplot as plt
df_plt_abnormal = df_plt.loc[df_plt['Abnormality'] != 'No finding']
sorted_desc = df_plt_abnormal.sort_values('Count',ascending=False)
plt.figure(figsize=(18,7))
ax = plt.subplot()
ax.set_axisbelow(True)
ax.grid(axis = 'y', color = 'green')
plt.bar(sorted_desc['Abnormality'], sorted_desc['Count'], color = 'red')
#plt.show()

# Rotate the x-labels by 30 degrees, and keep the text aligned horizontally
plt.xticks(rotation=90, horizontalalignment="center")
plt.tick_params(labelsize = 16)
plt.title("Chest XRay Training Data (15000 Images - 25971 unique image/label combinations)", fontsize = 20)
plt.xlabel("Lung Abnormality", fontsize = 16)
plt.ylabel("Training data labels", fontsize = 16)
plt.show()