# -*- coding: utf-8 -*-
"""TopXImagesperClass.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lc8BpqBJ5nPdwQYLuQi1bEdvSLLLVvHj
"""

from google.colab import drive
drive.mount('/content/drive')

pwd()

!ls '/content/drive/MyDrive/DAEN690/'

import pandas as pd
df = pd.read_csv ('/content/drive/MyDrive/DAEN690/train.csv')
print(df)

for classid in range(0, 15):
  print(classid)

s = df.groupby(['class_id', 'image_id']).size()
#.to_frame().reset_index()
s.to_frame().reset_index()

s = df.groupby(['class_id', 'image_id']).size()
df2 = s.to_frame().reset_index()
df2.columns = ['class_id', 'image_id', 'count']
indexSingle = df2[(df2['count'] == 1)].index
df2.drop(indexSingle, inplace=True)
df2 = df2.groupby(['class_id']).head(10)
df2

annotation_df = df.merge(df2, on=['class_id', 'image_id'])
annotation_df = annotation_df.drop(['rad_id', 'count'], axis=1)
annotation_df.drop_duplicates(inplace=True)
annotation_df.sort_values(['class_id', 'image_id'])

annotation_df.to_csv('/content/drive/MyDrive/DAEN690/annotation_sample.csv', index=False)

file_arr = annotation_df['image_id'].unique()
file_df = pd.DataFrame(file_arr, columns=['fname'])
file_df.to_csv('/content/drive/MyDrive/DAEN690/top10filesperclass.csv', index=False)

df.loc[df['image_id'] == '001d127bad87592efe45a5c7678f8b8d']

df.shape